export interface ProjLbImg {
    label: string;
    img: string;
    ghlink ?: string;
    deplink ?: string;
    auth: string;
    desc: string;
    used : string;
}

export const projectsList: ProjLbImg[] = [
    {
        label : "Number Roulette",
        img : "./nr.png",
        ghlink : "https://github.com/ArunavaCoderEm/Number-Roulette",
        deplink : "https://github.com/ArunavaCoderEm/Number-Roulette",
        auth: "Arunava Dutta",
        desc : "NumberRoulette is a web-based game.The game allows users to join a game room, enter an arena, and compete by spinning a lucky wheel to score points.",
        used : "React, TS, Websocket"

    },
    {
        label : "Vehycle",
        img : "./veh.png",
        ghlink : "https://github.com/ArunavaCoderEm/Vehycle",
        deplink : "https://vehycle.vercel.app/",
        auth: "Arunava Dutta",
        desc : "NumberRoulette is a web-based game.The game allows users to join a game room, enter an arena, and compete by spinning a lucky wheel to score points.",
        used : "Hono, MRN, TS, FB, TW"

    },
    {
        label : "RepXai",
        img : "./repx.jpg",
        ghlink : "https://github.com/Rep-X-AI/repx-ai",
        deplink : "https://repxai.vercel.app",
        auth: "Arunava Dutta",
        desc : "An AI-powered website for evaluating student marks, where teachers create assignments and students join, streamlining academic performance management and assessment.",
        used : "MERN, FB"

    },
    {
        label : "TaskEase",
        img : "./task.jpg",
        ghlink : "https://github.com/ArunavaCoderEm/TaskEase",
        deplink : "https://taskease-mu.vercel.app/",
        auth: "Arunava Dutta",
        desc : "TaskEase is a comprehensive todo manager website designed to streamline your task management process effortlessly with proprity tracker.",
        used : "MERN, TS, TW"
    },
    {
        label : "StudyGenie",
        img : "./ext.png",
        ghlink : "https://github.com/CodeFusers/frontend",
        deplink : "https://studygenie-cf.vercel.app",
        auth: "Arunava Dutta",
        desc : "Our website supports PDF, text, and YouTube video uploads to aid students with last-minute studies, offering detailed notes, summaries, and Q&A generated by our custom-built model.",
        used : "MERN, FB, TW"
    },
    {
        label : "Edemy",
        img : "./edm.png",
        ghlink : "https://github.com/eDemy-SIH/eDemy-Website",
        deplink : "https://edemy-32175.vercel.app",
        auth: "Arunava Dutta",
        desc : "In our software, we offer several free features, including an AI chat, multilingual support, career roadmap, and a psychometric test.",
        used : "HTML, CSS, JS"
    },
    {
        label : "PetMe",
        img : "./pet.png",
        ghlink : "https://github.com/ArunavaCoderEm/PetMe-Home-For-Pets",
        deplink : "https://petme-one.vercel.app",
        auth: "Arunava Dutta",
        desc : "Petme is a web-based platform where you can buy or sell pets of your choice. The website features functionalities like user sign-in and creating listings for pets available for sale.",
        used : "React, FB, TW"
    },
    {
        label : "NovelNest",
        img : "./novel.jpg",
        ghlink : "https://github.com/ArunavaCoderEm/Novel-Nest",
        deplink : "https://novelnest-seven.vercel.app",
        auth: "Arunava Dutta",
        desc : "A comprehensive online bookstore with a vast selection of books across all genres, featuring detailed descriptions, reviews, and personalized recommendations.",
        used : "ReactJS, TW"
    },
]